@startuml
'https://plantuml.com/class-diagram

'Inheritance
Window <|- Terminal
Import <|- FileImport
Import <|- WebImport

'Composition
Terminal *-- Toolbar
Terminal *-- Button
Terminal *-- Panel

'Aggregation

'Used as a base class for terminal, allows for drawing and sizing
'Implement non abstract then make it abstract
abstract class Window {
int x;
int y;
}

'Implement the Terminal as one class first, then break it out into separate modules
class Terminal {
}

class Toolbar {
}

class Button {
}

class Panel {
}

class Import {
}

class FileImport {
}

class WebImport {
}

class Company {
}

class Ticker {
}

abstract class Data {
}

@enduml